version: '3.9'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db 

  db:
    image: postgres:13  
    environment:
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_USER=ichsanmust
      - POSTGRES_DB=aratula_python
    volumes:
      - ./db_data:/var/lib/postgresql@13/data
    ports:
      - "5437:5432"
